#ifndef CONFIG_HACK4U
#define CONFIG_HACK4U

#define CHID "UANFAVTSAXZMYUWRECNAOJDAQVTTORVGJCCISMZYAFFU9EYLBMZKEJ9VNXVFFGUTCHONEYVWVUTBTDJLO"
#define NEW_CHID "ONMTPDICUWBGEGODWKGBGMLNAZFXNHCJITSSTBTGMXCXBXJFBPOPXFPOJTXKOOSAJOZAYANZZBFKYHJ9N"
#define EPID "KI99YKKLFALYRUVRXKKRJCPVFISPMNCQQSMB9BGUWIHZTYFQOBZWYSVRNKVFJLSPPLPSFNBNREJWOR99U"
#define TRYTES_81_1                                                            \
  "LCIKYSBE9IHXLIKCEJTTIQOTTAWSQCCQQ9A9VOKIWRBWVPXMCGUENWVVMQAMPEIVHEQ9JXLCNZ" \
  "OORVZTZ"

char ssid[] = "dlink-F67C-5GHz";       // your network SSID (name)
char pass[] = "asrlab65708";   // your network password
char gps_lat[] = "";   // 你所在的緯度
char gps_lon[] = "";  // 你所在的經度
const int lass_period = 60; // 幾秒想傳一次資料 建議實際上線是 60
//uint8_t iota_node[4] = {140, 116, 246, 164};

#endif
